services:
  network-deploy-services:
    networks:
      - eazybanks

  microservice-base-config:
    extends:
      service: network-deploy-services
    deploy:
      resources:
        limit:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configservice-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
